"""The Prop Desk: many accounts, one set of deterministic controls.

Eleven modules, arranged as one pipeline:

    Research Factory → Strategy Library → Strategy Health → Prop Account
    Compatibility → Strategy Allocation → Risk / Prop Rules Gate →
    Execution Fabric → Broker/API adapter → Account

`identity` separates provider, platform, venue, data feed and account, so a
front end is never mistaken for a place orders go. `credentials` holds the
pointer to a secret and never the secret. `instruments` maps a product to
another product with the arithmetic shown. `orders` is the event-driven order
and position lifecycle, built for events that duplicate, reorder and arrive
late. `fabric` is the one interface every provider is reached through, with a
per-credential rate budget, a priority queue and an outbox. `adapters` holds one
adapter that executes — against a local simulator, and it says so — and three
that declare their provider's real interface and refuse. `reconcile` treats the
provider as authoritative. `copy` is leader and followers, converging on net
position targets. `policy` answers what an account is *permitted* to do, four-
valued, where unknown is never permission. `allocation` chooses what runs where,
deterministically, with advice that can only narrow. `news` is scheduled
economic events from sources that permit being read. `desk` is the funnel every
order passes through, and the only path from an intent to an adapter.

Nothing here imports a broker client library, nothing here reaches a network
except the FRED calendar client, and `forge.execution.LIVE_EXECUTION_AVAILABLE`
remains `False`. No live broker execution exists in this build.
"""

from forge.propdesk.allocation import (
    AccountSnapshot,
    Advice,
    Allocation,
    AllocationChange,
    AllocationConstraints,
    AllocationError,
    AllocationPlan,
    Allocator,
    Candidate,
    FeasibilityCheck,
    FeasibilityReason,
    HealthGrade,
    StrategyHealth,
    diff_allocations,
    grade_health,
    use_case_for,
)
from forge.propdesk.audit import (
    Actor as AuditActor,
)
from forge.propdesk.audit import (
    ApprovalState,
    AuditAction,
    ConsequentialRecord,
)
from forge.propdesk.autonomy import (
    MANDATORY_GATES,
    AutonomyLevel,
    DeploymentDecision,
    DeploymentFacts,
    Gate,
    GateKind,
    GateOutcome,
    describe_gates,
    describe_levels,
)
from forge.propdesk.autonomy import (
    Outcome as DeploymentOutcome,
)
from forge.propdesk.consent import (
    DISCLOSURES,
    ConsentError,
    Disclosure,
    DisclosureKey,
)
from forge.propdesk.consent import (
    Acknowledgement as DisclosureAcknowledgement,
)
from forge.propdesk.consent import (
    current_version as current_disclosure_version,
)
from forge.propdesk.consent import (
    is_current as disclosure_is_current,
)
from forge.propdesk.consent import (
    require as require_acknowledgement,
)
from forge.propdesk.copy import (
    CopyDecision,
    CopyError,
    CopyGroup,
    CopyHealth,
    CopyOutcome,
    CopyResolver,
    ExecutionMode,
    Follower,
    GroupPolicy,
    Leader,
    SizingMethod,
    SizingPolicy,
    assess_health,
    new_group_id,
)
from forge.propdesk.credentials import (
    REDACTED,
    CredentialBroker,
    CredentialError,
    CredentialRecord,
    EnvironmentResolver,
    Secret,
    SecretSource,
    SessionResolver,
    new_credential_ref,
    redact,
    required_roles,
)
from forge.propdesk.desk import (
    DeskAccount,
    DeskContext,
    DeskDecision,
    DeskError,
    PropDesk,
    Stage,
    cleared,
    refused,
    summarise,
)
from forge.propdesk.fabric import (
    Acknowledgement,
    AdapterHealth,
    AdapterUnavailable,
    CommandKind,
    ConnectionRuntime,
    ExecutionAdapter,
    ExecutionFabric,
    FabricError,
    OrderIntent,
    Outbox,
    Priority,
    ProviderSnapshot,
    RateBudget,
)
from forge.propdesk.identity import (
    PLATFORM_BINDINGS,
    PROVIDER_DESCRIPTORS,
    Account,
    AccountCapability,
    AccountKey,
    AccountType,
    AuthMethod,
    BracketModel,
    BrokerConnection,
    ConnectionState,
    DataFeed,
    Environment,
    ExecutionVenue,
    Platform,
    PlatformBinding,
    Provider,
    ProviderDescriptor,
    VenueKind,
    binding,
    catalogue,
    descriptor,
    new_connection_id,
    provider_for_platform,
)
from forge.propdesk.instruments import (
    CME_INSTRUMENTS,
    Contract,
    Instrument,
    InstrumentCatalogue,
    MappedQuantity,
    MappingError,
    MappingPolicy,
    ProviderSymbol,
    RollWindow,
    Rounding,
    default_catalogue,
    parse_exchange_symbol,
)
from forge.propdesk.news import (
    FRED_ATTRIBUTION,
    SUGGESTED_SOURCES,
    Availability,
    CalendarError,
    CalendarProvider,
    CalendarRegistry,
    EconomicEvent,
    FredReleaseCalendar,
    Impact,
    ManualCalendar,
    NewsAssessment,
    NewsPolicy,
    assess_news,
    classify_impact,
)
from forge.propdesk.orders import (
    Applied,
    BracketRole,
    LifecycleError,
    OrderEvent,
    OrderEventType,
    OrderMachine,
    OrderOrigin,
    OrderRecord,
    OrderState,
    OrderType,
    Position,
    PositionChange,
    PositionState,
    PositionTransition,
    Side,
    TimeInForce,
    apply_fill,
    classify_transition,
    idempotency_key,
    new_order_id,
)
from forge.propdesk.policy import (
    POLICY_QUESTIONS,
    CompatibilityReason,
    CompatibilityReport,
    DirectionGuard,
    Permission,
    PropProgramPolicy,
    StrategyRequirements,
    UseCase,
    evaluate_compatibility,
    worst,
)
from forge.propdesk.policy import (
    OrderOrigin as PolicyOrderOrigin,
)
from forge.propdesk.reconcile import (
    Divergence,
    DivergenceKind,
    LocalView,
    ReconciliationEngine,
    ReconciliationPolicy,
    ReconciliationReport,
    ReconciliationState,
    Severity,
    Trigger,
    orphan_orders,
)
from forge.propdesk.risk import (
    PROHIBITIONS,
    AiCapability,
    ManualRisk,
    Prohibition,
    RiskBoundaries,
    RiskError,
    RiskMode,
    RiskSettings,
    capability_catalogue,
    describe_modes,
    prohibition_catalogue,
)
from forge.propdesk.scaling import (
    Clamp,
    Direction,
    Driver,
    DriverKind,
    RiskObservation,
    RiskProposal,
    ScalingState,
    drivers_for,
    explain,
    propose,
)
from forge.propdesk.store import PropDeskStore
from forge.propdesk.survival import (
    DrawdownDistribution,
    RiskBand,
    Unmeasurable,
    appetite_quantile,
    derive_band,
    drawdown_distribution,
)

__all__ = [
    "CME_INSTRUMENTS",
    "DISCLOSURES",
    "FRED_ATTRIBUTION",
    "MANDATORY_GATES",
    "PLATFORM_BINDINGS",
    "POLICY_QUESTIONS",
    "PROHIBITIONS",
    "PROVIDER_DESCRIPTORS",
    "REDACTED",
    "SUGGESTED_SOURCES",
    "Account",
    "AccountCapability",
    "AccountKey",
    "AccountSnapshot",
    "AccountType",
    "Acknowledgement",
    "AdapterHealth",
    "AdapterUnavailable",
    "Advice",
    "AiCapability",
    "Allocation",
    "AllocationChange",
    "AllocationConstraints",
    "AllocationError",
    "AllocationPlan",
    "Allocator",
    "Applied",
    "ApprovalState",
    "AuditAction",
    "AuditActor",
    "AuthMethod",
    "AutonomyLevel",
    "Availability",
    "BracketModel",
    "BracketRole",
    "BrokerConnection",
    "CalendarError",
    "CalendarProvider",
    "CalendarRegistry",
    "Candidate",
    "Clamp",
    "CommandKind",
    "CompatibilityReason",
    "CompatibilityReport",
    "ConnectionRuntime",
    "ConnectionState",
    "ConsentError",
    "ConsequentialRecord",
    "Contract",
    "CopyDecision",
    "CopyError",
    "CopyGroup",
    "CopyHealth",
    "CopyOutcome",
    "CopyResolver",
    "CredentialBroker",
    "CredentialError",
    "CredentialRecord",
    "DataFeed",
    "DeploymentDecision",
    "DeploymentFacts",
    "DeploymentOutcome",
    "DeskAccount",
    "DeskContext",
    "DeskDecision",
    "DeskError",
    "Direction",
    "DirectionGuard",
    "Disclosure",
    "DisclosureAcknowledgement",
    "DisclosureKey",
    "Divergence",
    "DivergenceKind",
    "DrawdownDistribution",
    "Driver",
    "DriverKind",
    "EconomicEvent",
    "Environment",
    "EnvironmentResolver",
    "ExecutionAdapter",
    "ExecutionFabric",
    "ExecutionMode",
    "ExecutionVenue",
    "FabricError",
    "FeasibilityCheck",
    "FeasibilityReason",
    "Follower",
    "FredReleaseCalendar",
    "Gate",
    "GateKind",
    "GateOutcome",
    "GroupPolicy",
    "HealthGrade",
    "Impact",
    "Instrument",
    "InstrumentCatalogue",
    "Leader",
    "LifecycleError",
    "LocalView",
    "ManualCalendar",
    "ManualRisk",
    "MappedQuantity",
    "MappingError",
    "MappingPolicy",
    "NewsAssessment",
    "NewsPolicy",
    "OrderEvent",
    "OrderEventType",
    "OrderIntent",
    "OrderMachine",
    "OrderOrigin",
    "OrderRecord",
    "OrderState",
    "OrderType",
    "Outbox",
    "Permission",
    "Platform",
    "PlatformBinding",
    "PolicyOrderOrigin",
    "Position",
    "PositionChange",
    "PositionState",
    "PositionTransition",
    "Priority",
    "Prohibition",
    "PropDesk",
    "PropDeskStore",
    "PropProgramPolicy",
    "Provider",
    "ProviderDescriptor",
    "ProviderSnapshot",
    "ProviderSymbol",
    "RateBudget",
    "ReconciliationEngine",
    "ReconciliationPolicy",
    "ReconciliationReport",
    "ReconciliationState",
    "RiskBand",
    "RiskBoundaries",
    "RiskError",
    "RiskMode",
    "RiskObservation",
    "RiskProposal",
    "RiskSettings",
    "RollWindow",
    "Rounding",
    "ScalingState",
    "Secret",
    "SecretSource",
    "SessionResolver",
    "Severity",
    "Side",
    "SizingMethod",
    "SizingPolicy",
    "Stage",
    "StrategyHealth",
    "StrategyRequirements",
    "TimeInForce",
    "Trigger",
    "Unmeasurable",
    "UseCase",
    "VenueKind",
    "appetite_quantile",
    "apply_fill",
    "assess_health",
    "assess_news",
    "binding",
    "capability_catalogue",
    "catalogue",
    "classify_impact",
    "classify_transition",
    "cleared",
    "current_disclosure_version",
    "default_catalogue",
    "derive_band",
    "describe_gates",
    "describe_levels",
    "describe_modes",
    "descriptor",
    "diff_allocations",
    "disclosure_is_current",
    "drawdown_distribution",
    "drivers_for",
    "evaluate_compatibility",
    "explain",
    "grade_health",
    "idempotency_key",
    "new_connection_id",
    "new_credential_ref",
    "new_group_id",
    "new_order_id",
    "orphan_orders",
    "parse_exchange_symbol",
    "prohibition_catalogue",
    "propose",
    "provider_for_platform",
    "redact",
    "refused",
    "require_acknowledgement",
    "required_roles",
    "summarise",
    "use_case_for",
    "worst",
]
